Repository anniversaryArchive/archive_app, pull requests merged in 2022-07, with the labels that each got.

#3 Docs: Create pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 문서

#4 GetX + GraphQL Setting
  lib/api/common_query.dart
  lib/api/mutations.dart
  lib/api/queries.dart
  lib/controllers/artist_controller.dart
  lib/main.dart
  lib/screens/home_screen.dart
  lib/services/graphql_service.dart
  pubspec.yaml
Labels: enhancement

#8 package name & Bundle ID 수정
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/anniversary/archive/archive/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
Labels: Setting

#10 Feat/default appbar
  analysis_options.yaml
  lib/layouts/default_appbar.dart
  lib/screens/home_screen.dart
Labels: Feature

#11 Feat/models
  lib/common/config.dart
  lib/models/artist.dart
  lib/models/artist.g.dart
  lib/models/group.dart
  lib/models/group.g.dart
  pubspec.yaml
Labels: Feature

#12 [Feat] 아티스트 선택 화면 구현
  lib/api/common_query.dart
  lib/api/queries.dart
  lib/common/config.dart
  lib/common/functions.dart
  lib/components/custom_loading.dart
  lib/controllers/artist_controller.dart
  lib/controllers/data_controller.dart
  lib/main.dart
  lib/models/artist.dart
  lib/models/group.dart
  lib/models/group.g.dart
  lib/screens/select_artist/components/artist_item.dart
  lib/screens/select_artist/select_artist_screen.dart
  lib/services/graphql_service.dart
Labels: Feature

#14 [Feat] 트위터 로그인 구현
  .gitignore
  android/app/src/main/AndroidManifest.xml
  assets/icons/twitter.png
  ios/Runner/Info.plist
  lib/dialogs/login_dialog.dart
  lib/main.dart
  lib/screens/home_screen.dart
  pubspec.yaml
Labels: Feature

#18 [Feat] 카카오 맵 추가
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/main.dart
  lib/models/archive.dart
  lib/models/archive.g.dart
  lib/screens/archive/archive_screen.dart
  lib/screens/archive/components/map_view.dart
  pubspec.yaml
Labels: Feature

#19 [Feat] 그룹 내 아티스트 선택 화면 구현
  lib/api/common_query.dart
  lib/api/queries.dart
  lib/controllers/data_controller.dart
  lib/layouts/default_appbar.dart
  lib/main.dart
  lib/screens/select_artist/select_artist_screen.dart
  lib/screens/select_artist_in_group/components/select_group_artist_item.dart
  lib/screens/select_artist_in_group/select_group_artist_screen.dart
  lib/utils/date_helper.dart
  pubspec.yaml
Labels: Feature
